services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU26-ubuntu-22.04
    container_name: ib230120-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-YourStrong!Passw0rd1}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ib230120
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: ib230120-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-admin}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-admin}"
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management
    expose:
      - 5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ib230120
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  flix-api:
    build:
      context: .
    container_name: ib230120-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${MSSQL_DB:-230120};User Id=sa;Password=${MSSQL_SA_PASSWORD:-YourStrong!Passw0rd1};TrustServerCertificate=True;MultipleActiveResultSets=True
      - ConnectionStrings__RabbitMQ=host=rabbitmq;username=${RABBITMQ_USER:-admin};password=${RABBITMQ_PASS:-admin}
    env_file:
      - path: .env
        required: false
    ports:
      - "5071:5121"
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ib230120
    restart: unless-stopped

  flix-subscriber:
    build:
      context: .
      dockerfile: Flix.Subscriber/Dockerfile
    container_name: ib230120-subscriber
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DATABASE_CONNECTION=Server=sqlserver;Database=${MSSQL_DB:-230120};User Id=sa;Password=${MSSQL_SA_PASSWORD:-YourStrong!Passw0rd1};TrustServerCertificate=True;MultipleActiveResultSets=True
      - RABBITMQ_HOST=rabbitmq
    env_file:
      - path: .env
        required: True
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ib230120
    restart: unless-stopped

volumes:
  sqlserver_data:
  rabbitmq_data:

networks:
  ib230120:
    driver: bridge
